# Generated by Django 6.0.4 on 2026-05-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('SUSPICIOUS', 'SUSPICIOUS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20),
        ),
    ]
